[package]
name = "robust_compare"
version = "0.1.0"
authors = ["Titus Tienaah <titus.intdxdt@gmail.com>"]

[dependencies]
robust_subtract= { git = "https://github.com/intdxdt/robust_subtract", branch = "master" }